#include QMK_KEYBOARD_H

// Helpful defines
#define _______ KC_TRNS

// tap dance declarations
enum {
  TD_SLSH_BSLS = 0,
};


//tap dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
  [TD_SLSH_BSLS]  = ACTION_TAP_DANCE_DOUBLE(KC_SLSH, KC_BSLS),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = KEYMAP(KC_SLEP, LCTL(KC_DOWN), LCTL(KC_UP), KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU, KC_F11, KC_F12, KC_EJCT, KC_LBRC, KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_RBRC, KC_CAPS, KC_A, KC_R, KC_S, KC_T, KC_D, KC_H, KC_N, KC_E, KC_I, KC_O, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, TD(TD_SLSH_BSLS), KC_RSFT, TG(2), LCTL_T(KC_GRV), LALT_T(KC_TAB), KC_LEFT, KC_RGHT, LGUI_T(KC_BSPC), LT(1, KC_ESC), RGUI_T(KC_ENT), RSFT_T(KC_SPC), KC_UP, KC_DOWN, KC_MINS, KC_EQL, TG(3)),
	[1] = KEYMAP(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PCMM, KC_PDOT, KC_PSLS, KC_NO, KC_NO, KC_LCTL, KC_LALT, KC_LEFT, KC_RGHT, LGUI_T(KC_BSPC), KC_TRNS, RGUI_T(KC_ENT), RSFT_T(KC_SPC), KC_UP, KC_DOWN, KC_PMNS, KC_PPLS, KC_NO),
	[2] = KEYMAP(KC_ACL0, KC_ACL1, KC_ACL2, KC_BTN3, KC_BTN4, KC_BTN5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_ESC, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_WH_L, KC_WH_D, KC_WH_R, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, LCTL_T(KC_GRV), LALT_T(KC_TAB), KC_LEFT, KC_RGHT, LGUI_T(KC_BSPC), KC_BTN1, KC_BTN2, RSFT_T(KC_SPC), KC_UP, KC_DOWN, KC_NO, KC_NO, KC_NO),
	[3] = KEYMAP(KC_NO, RGB_RMOD, RGB_MOD, RGB_HUD, RGB_HUI, RGB_SAD, RGB_SAI, RGB_VAD, RGB_VAI, RGB_SPD, RGB_SPI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, KC_NO, KC_NO, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, KC_NO, BL_STEP, BL_ON, BL_OFF, BL_DEC, BL_INC, BL_BRTG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, KC_NO, KC_NO, BL_TOGG, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS)
};
